# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-06 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import newsapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('article', models.TextField(verbose_name=newsapp.models.ArticlesManager)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
                ('nltk_score', models.IntegerField(default=0)),
                ('source', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
            ],
        ),
    ]
