# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-05 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='homepage',
        ),
    ]
